### ISSUE TITLE
Option to disable Swap feature

### ISSUE THREAD

**Issue by T-256** [davidKolar175/fast-compare#2]
![image](https://github.com/davidKolar175/fast-compare/assets/132141463/693dcfc0-01fa-4230-9db6-5c56dd7e8591)

Since it has supported natively.

**Comment by T-256** [comment]
for temporary workaround, you can hide it via right click on it:
![image](https://github.com/davidKolar175/fast-compare/assets/132141463/136c4886-c59f-4470-8762-9f66ad6bf0cd)

**Comment by davidKolar175** [comment]
> for temporary workaround, you can hide it via right click on it: ![image](https://private-user-images.githubusercontent.com/132141463/317066797-136c4886-c59f-4470-8762-9f66ad6bf0cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjAxMDEsIm5iZiI6MTcxMTUxOTgwMSwicGF0aCI6Ii8xMzIxNDE0NjMvMzE3MDY2Nzk3LTEzNmM0ODg2LWM1OWYtNDQ3MC04NzYyLTlmNjZhZDZiZjBjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNjEwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Yzk4Mjg1MWJmZTA2ZmUzMjgwZjcwMDBjZGJiNjlmYTQ3OTYxYTdmZjhhMTQwYzJhMDlmNDkwYjI3ZDI1OWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3-DN-tQ2Z2jGoNWez18q7oA1RUzO1N3LVaLrd6_C5Z0)

Is this a new feature in VS that came in an update? Never noticed it.
